LearnEnglishTenses/LearnEnglishTenses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('learntenses.urls')),
]

LearnEnglishTenses/learntenses/urls.py
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('landing/', views.landing, name='landing'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<str:tense_name>/learn', views.learn_tense, name='learn_tense'), 
    path('<str:tense_name>/tasks', views.task_list, name='task_list'),
    path('<str:tense>/task/<int:task_id>', views.task_detail, name='task_detail'),
    path('increment_attempts/<int:task_id>/', views.increment_attempts, name='increment_attempts'),
    path('mark_as_completed/<int:task_id>/', views.mark_as_completed, name='mark_as_completed'),
    path('reset_attempts/<int:task_id>/', views.reset_attempts, name='reset_attempts'),
    path('create_task/', views.create_task, name='create_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('manage_tasks/', views.manage_tasks, name='manage_tasks'),
]

LearnEnglishTenses/learntenses/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    date_joined = models.DateTimeField(auto_now_add=True)

    def completed_tasks_by_tense(self):
        return self.usertask_set.filter(completed=True).values('task__tense').annotate(count=models.Count('task__tense'))

    def __str__(self):
        return self.user.username

class Task(models.Model):
    TENSE_CHOICES = [
        ('PS', 'Present Simple'),
        ('PC', 'Present Continuous'),
        ('PP', 'Present Perfect'),
    ]
    TASK_NAMES = [
        ('1', 'Task 1'),
        ('2', 'Task 2'),
        ('3', 'Task 3'),
        ('4', 'Task 4'),
        ('5', 'Task 5'),
        ('6', 'Task 6')
    ]
    LEVELS = {
        '1' : 1,
        '2' : 2,
        '3' : 3,
        '4' : 4,
        '5' : 5,
        '6' : 6,
    }
        
    level = models.IntegerField(blank=True, null=True) 
    tense = models.CharField(max_length=3, choices=TENSE_CHOICES)
    name = models.CharField(max_length=10, choices=TASK_NAMES)
    sentence = models.CharField(max_length=500)
    words = models.CharField(max_length=500)
    correct_words = models.CharField(max_length=500)

    class Meta:
        unique_together = ('name', 'tense')

    def __str__(self):
        return f"{self.get_tense_display()} - {self.get_name_display()}"
    
    def save(self, *args, **kwargs):
        self.level = self.LEVELS[self.name]
        is_new = self.pk is None
        super().save(*args, **kwargs) 
        if is_new:
            for user_profile in UserProfile.objects.all():
                UserTask.objects.create(user=user_profile, task=self)

    def get_level(self):
        return int(self.name)

class UserTask(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE) 
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    attempts = models.IntegerField(default=0)
 
    def __str__ (self):
        return f"{self.user} - {self.task}"
    
    def mark_as_completed(self):
        self.completed = True
        self.save()

    def check_attempts(self):
        return self.attempts>=3
    
    def reset_attempts(self):
        self.attempts = 0
        self.save()

class TaskForm(forms.Form):
    tense = forms.CharField(required=True)
    name = forms.CharField(required=True)
    sentence = forms.CharField(widget=forms.Textarea, required=True)
    words = forms.CharField(widget=forms.Textarea, required=True)
    correct_words = forms.CharField(widget=forms.Textarea, required=True)

LearnEnglishTenses/learntenses/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile, Task

class UserRegisterForm(UserCreationForm):
    name = forms.CharField(max_length=30)
    age = forms.IntegerField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'name', 'age']

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            UserProfile.objects.create(user=user, name=self.cleaned_data["name"], age=self.cleaned_data["age"])
        return user

class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'age']

    def __init__(self, *args, **kwargs):
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        self.label_suffix = "" 

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.label_suffix = "" 

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['level', 'tense', 'name', 'sentence', 'words', 'correct_words']

LearnEnglishTenses/learntenses/views.py
from django.contrib.auth import authenticate, login as auth_login, update_session_auth_hash
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from .forms import UserRegisterForm, UserProfileEditForm, UserEditForm, TaskForm
from .models import UserProfile, Task, UserTask
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods, require_POST
from django.http import JsonResponse
from django.db import IntegrityError


def index(request):
    return render(request, 'learntenses/homepage.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            age = form.cleaned_data.get('age')
            new_user.userprofile.age = age
            new_user.userprofile.save()
            tasks = Task.objects.all()
            for task in tasks:
                UserTask.objects.create(user=new_user.userprofile, task=task) 
            return redirect('home:login')
    else:  
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)  
                return redirect('home:index')
            else:
                return redirect('home:login')
    else:  
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})
    
def logout(request):
    auth_logout(request)
    return redirect('home:landing')

def landing(request):
    return render(request, 'learntenses/landing.html')

def profile(request):
    return render(request, 'learntenses/profile.html')

def edit_profile(request):
    if not hasattr(request.user, 'userprofile'):
        UserProfile.objects.create(user=request.user, age=0) 
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = UserProfileEditForm(request.POST, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('home:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = UserProfileEditForm(instance=request.user.userprofile)
    return render(request, 'learntenses/edit_profile.html', {'user_form': user_form, 'profile_form': profile_form})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            return redirect('home:profile')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'learntenses/change_password.html', {'form': form})

def task_list(request, tense_name):
    tense_mapping = {
        'present_simple': 'PS',
        'present_continuous': 'PC',
        'present_perfect': 'PP',
        'past_simple': 'PaS',
        'past_continuous': 'PaC',
        'past_perfect': 'PaP',
        'future_simple': 'FS',
        'future_continuous': 'FC',
        'future_perfect': 'FP',
    }
    tense_name_mapping = {
        'present_simple': 'Present Simple',
        'present_continuous': 'Present Continuous',
        'present_perfect': 'Present Perfect',
        'past_simple': 'Past Simple',
        'past_continuous': 'Past Continuous',
        'past_perfect': 'Past Perfect',
        'future_simple': 'Future Simple',
        'future_continuous': 'Future Continuous',
        'future_perfect': 'Future Perfect',
    }
    tense = tense_mapping.get(tense_name)
    tasks = Task.objects.filter(tense=tense).order_by('name')  
    user_profile = UserProfile.objects.get(user=request.user)
    user_tasks = list(UserTask.objects.filter(user=user_profile, task__in=tasks).order_by('task__name'))
    if user_tasks:
        user_tasks[0].locked = False 
        for i in range(1, len(user_tasks)):
            user_tasks[i].locked = not user_tasks[i-1].completed
    return render(request, 'learntenses/task_list.html', {'tasks': tasks, 'user_tasks': user_tasks, 'tense_name': tense_name_mapping.get(tense_name)})

def replace_with_span(sentence):
    words = sentence.split()
    for i, word in enumerate(words):
        if '<>' in word:
            words[i] = word.replace('<>', '<span class="blank" style="font-weight: bold;">_____</span>')
    return ' '.join(words)

@csrf_exempt
@require_http_methods(['GET','POST'])
def task_detail(request, tense, task_id):
    task = get_object_or_404(Task, id=task_id, tense=tense)
    user_profile = UserProfile.objects.get(user=request.user)
    user_task = get_object_or_404(UserTask, user=user_profile, task=task)
    task.sentence = replace_with_span(task.sentence)
    previous_task = Task.objects.filter(id__lt=task_id, tense=tense).order_by('-id').first()

    if not user_task.completed and (previous_task is not None and not UserTask.objects.filter(user=user_profile, task=previous_task, completed=True).exists()):
        return HttpResponseForbidden()

    return render(request, 'learntenses/task_detail.html', {'task': task, 'user_task': user_task, 'attempts_reached' : user_task.check_attempts()})

@csrf_exempt
def increment_attempts(request, task_id):
    user_profile = UserProfile.objects.get(user=request.user)
    task = get_object_or_404(Task, id=task_id)
    user_task = get_object_or_404(UserTask, user=user_profile, task=task)

    user_task.attempts += 1
    user_task.save()

    attempts_reached = user_task.check_attempts()

    return JsonResponse({'status': 'success', 'attempts_reached': attempts_reached})

@csrf_exempt
def reset_attempts(request, task_id):
    if request.method == 'POST':
        try:
            user_profile = UserProfile.objects.get(user=request.user)
            user_task = UserTask.objects.get(user=user_profile, task_id=task_id)
            user_task.reset_attempts()
            return JsonResponse({'status': 'success'})
        except UserTask.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'UserTask not found'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

@csrf_exempt
@require_POST
def mark_as_completed(request, task_id):
    user_task = get_object_or_404(UserTask, user=request.user.userprofile, task_id=task_id)
    user_task.mark_as_completed()
    return JsonResponse({'status': 'success'})

def create_task(request):
    tasks = Task.objects.all()
    tenses = {choice[0]: [] for choice in Task.TENSE_CHOICES}
    for task in tasks:
        tenses[task.tense].append(task)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('home:create_task')
            except IntegrityError:
                form.add_error(None, 'A task with this name already exists for this tense')

    else:
        form = TaskForm()
    return render(request, 'learntenses/create_task.html', {'form': form, 'tenses':tenses})

def manage_tasks(request):
    tasks = Task.objects.all()
    tenses = {choice[0]: [] for choice in Task.TENSE_CHOICES}

    present_tenses = ['PS', 'PC', 'PP']
    past_tenses = ['PaS', 'PaC', 'PaP']
    future_tenses = ['FS', 'FC', 'FP']

    for task in tasks:
        tenses[task.tense].append(task)
    return render(request, 'learntenses/manage_tasks.html', {'tenses': tenses, 'present_tenses': present_tenses, 'past_tenses': past_tenses, 'future_tenses': future_tenses})

@require_POST
def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('home:create_task')

def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('home:manage_tasks')
    else:
        form = TaskForm(instance=task)

    tense_mapping = {
        'PS': 'Present Simple',
        'PC': 'Present Continuous',
        'PP': 'Present Perfect',
    }

    full_tense = tense_mapping.get(task.tense, task.tense)

    return render(request, 'learntenses/edit_task.html', {'form': form, 'full_tense': full_tense})

def learn_tense(request, tense_name):
    template_name = f'learntenses/learn_{tense_name}.html'
    return render(request, template_name)

LearnEnglishTenses/learntenses/templates/learntenses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Learn English Tenses</title>
  {% load static %}
  <link href="{% static 'learntenses/styles/base.css' %}" rel="stylesheet">
  {% block extra_css %}
  {% endblock %}
</head>
<body>
  <div class="container">
    <div class="navigation">
      <h1>Learn English Tenses</h1>
      {% if request.user.is_superuser %}
        <a href="{% url 'admin:index' %}">
          <img class="icon" src="{% static 'learntenses/images/admin-panel.png' %}" alt="">
          Admin Panel
        </a>
        {% if request.user.is_authenticated %}
          <a href="{% url 'home:create_task' %}">
            <img class="icon" src="{% static 'learntenses/images/plus.png' %}" alt="">
            Create tasks
          </a>
          <a href="{% url 'home:manage_tasks' %}">
            <img class="icon" src="{% static 'learntenses/images/manage.png' %}" alt="">
            Manage tasks
          </a>
          <form id="logout-form" method="POST" action="{% url 'home:logout' %}">
            {% csrf_token %}
          </form>
          <a href="#" onclick="document.getElementById('logout-form').submit();">
            <img class="icon" src="{% static 'learntenses/images/logout.png' %}" alt="">
            Logout
          </a>
        {% endif %}
      {% else %}
        <a href="{% url 'home:index' %}">
          <img class="icon" src="{% static 'learntenses/images/home.png' %}" alt="">
          Home
        </a>
        <a href="#" id="learn-tenses">
          <img class="icon" src="{% static 'learntenses/images/learn.png' %}" alt="">
          Learn
        </a>
        <div id="tenses" style="display: none;">
          <a href="{% url 'home:learn_tense' 'present_simple' %}">Present Simple</a>
          <a href="{% url 'home:learn_tense' 'present_continous' %}">Present Continuous</a>
          <a href="{% url 'home:learn_tense' 'present_perfect' %}">Present Perfect</a>
        </div>
        <a href="#" id="solve-tasks">
          <img class="icon" src="{% static 'learntenses/images/solve-tasks.png' %}" alt="">
          Solve tasks
        </a>
        <div id="tasks" style="display: none;">
          <a href="{% url 'home:task_list' 'present_simple' %}">Present Simple</a>
          <a href="{% url 'home:task_list' 'present_continuous' %}">Present Continuous</a>
          <a href="{% url 'home:task_list' 'present_perfect' %}">Present Perfect</a>
        </div>
        <a href="{% url 'home:profile' %}">
          <img class="icon" src="{% static 'learntenses/images/profile.png' %}" alt="">
          Profile
        </a>
        {% if request.user.is_authenticated %}
          <form id="logout-form" method="POST" action="{% url 'home:logout' %}">
            {% csrf_token %}
          </form>
          <a href="#" onclick="document.getElementById('logout-form').submit();">
            <img class="icon" src="{% static 'learntenses/images/logout.png' %}" alt="">
            Logout
          </a>
        {% endif %}
      {% endif %}
      <div class="icon-credit">
        <p class="small-text">Icons by Icons8</p>
      </div>
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <script src="{% static 'learntenses/js/scripts.js' %}">

  </script>
</body>
</html>

LearnEnglishTenses/learntenses/templates/learntenses/change_password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link href="{% static 'learntenses/styles/change_password.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="back-button">
      <a href="{% url 'home:edit_profile' %}">
        <button class="back-btn">Back</button>
      </a>
    </div>
    <div class="change-pwd-header">
      <h2>Change your password</h2>
    </div>
    <div class="change-pwd-container">
      <form method="POST" action="{% url 'home:change_password' %}">
        {% csrf_token %}
        <div class="form-field">
          <label for="{{ form.old_password.id_for_label }}">Old password</label>
          {{ form.old_password }}
        </div>
        <div class="form-field">
          <label for="{{ form.new_password1.id_for_label }}">New password</label>
          {{ form.new_password1 }}
        </div>
        <div class="form-field">
          <label for="{{ form.new_password2.id_for_label }}">Confirm new password</label>
          {{ form.new_password2 }}
        </div>
        <button type="submit" class="change-pwd-btn">Change password</button>
      </form>
    </div>
    {% for field in form %}
      {% for error in field.errors %}
        <div class="error">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  </body>
</html>

LearnEnglishTenses/learntenses/templates/learntenses/edit_profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static 'learntenses/styles/edit_profile.css' %}" rel="stylesheet">
    <title>Edit your profile</title>
  </head>
  <body>
    <div class="back-button">
      <a href="{% url 'home:profile' %}">
        <button class="back-btn">Back</button>
      </a>
    </div>
    <div class="edit-profile-header">
      <h2>Edit your profile</h2>
    </div>
    <div class="edit-profile-container">
      <form method="POST" action="{% url 'home:edit_profile' %}">
        {% csrf_token %}
        <div class="form-field">
          {{ user_form.username.label_tag }}
          {{ user_form.username }}
        </div>
        <div class="form-field">
          {{ user_form.email.label_tag }}
          {{ user_form.email }}
        </div>
        <div class="form-field">
          {{ profile_form.name.label_tag }}
          {{ profile_form.name }}
        </div>
        <div class="form-field">
          {{ profile_form.age.label_tag }}
          {{ profile_form.age }}
        </div>
        <button type="submit" class="save-btn">Save changes</button>
      </form>
    </div>
    <div class="change-password">
      <h2>Want to change your password?</h2>
      <a href="{% url 'home:change_password' %}">Click here!</a>
    </div>
  </body>
</html>

LearnEnglishTenses/learntenses/templates/learntenses/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to Learn English Tenses!</title>
  {% load static %}
  <link href="{% static 'learntenses/styles/landing.css' %}" rel="stylesheet">
</head>
<body>
  <div class="header-landing">
    <h1>Learn English Tenses</h1>
  </div>
  <div class="container-landing">
    <div>
      <p>A fun and effective way to learn English tenses, for free!</p>
    </div>
    <div class="buttons-landing">
      <a href="{% url 'home:register' %}">
        <div>
          <button class="register-btn">GET STARTED</button>
        </div>
      </a>
      <a href="{% url 'home:login' %}">
        <div>
          <button class="login-btn">I ALREADY HAVE AN ACCOUNT</button>
        </div>
      </a>
    </div>
  </div>
</body>
</html>

LearnEnglishTenses/learntenses/templates/learntenses/learn_present_continous.html
{% extends 'learntenses/base.html' %}

{% block extra_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'learntenses/styles/tense.css' %}">
{% endblock %}

{% block content %}

<div class="learn-container">
  <div class="learn-header">
    <div>
      <h2>Present continuous tense</h2>  
    </div>
    <div>
      <div class="learn-art">
          <div class="edit-info">
            <img class="art" src="{% static 'learntenses/images/learn_art.png' %}" alt="">
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="learn-body">
    <div class="definition">
      <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
      <p class="p-desc">
        The <span>Present continuous</span> verb tense indicates that an action or condition is happening right now, frequently, and may continue into the future.
      </p>
    </div>
    <div class="use-of">
      <div>
        <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
        <h3>Present continuous usage</h3>
      </div>
      <div>
        <ul class="use-of-ul">
          <li class="list-item">Actions happening at the moment of speaking</li>
            <ul>
              <li>
                Peter <span class="auxiliary">is</span> <span class="infinitive">read</span><span class="ending">ing</span> a book now.
              </li>
            </ul>
          <li class="list-item">Fixed plans in the near future</li>
            <ul>
              <li>We <span class="auxiliary">are</span> <span class="infinitive">go</span><span class="ending">ing</span> to Basel on Saturday.</li>
            </ul>
          <li class="list-item">Temporary actions</li>
            <ul>
              <li>I <span class="auxiliary">am</span> <span class="infinitive">work</span><span class="ending">ing</span> in Rome this month.</li>
            </ul>
          <li class="list-item">Actions happening around the moment of speaking (longer actions)</li>
            <ul>
              <li>My friend <span class="auxiliary">is</span> <span class="infinitive">prepar</span><span class="ending">ing</span> for his exams.</li>
            </ul>
          <li class="list-item">Repeated actions which are irritating to the speaker (with always, constantly, forever)</li>
            <ul>
              <li>Andrew <span class="auxiliary">is</span> always <span class="infinitive">com</span><span class="ending">ing</span> late.</li>
            </ul>
          
        </ul>
      </div>
    </div>
    <div class="signal-words">
      <div>
        <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
        <h3>Signal words</h3>
      </div>
        <p>Signal words are keywords or phrases that provide clues about the timing and 
          frequency of the action described in a sentence. 
          They help identify the tense that should be used.</p>
      <div>
        <ul class="signal-words-ul">
          <li class="list-item">now</li>
          <li class="list-item">at the moment</li>
          <li class="list-item">Look!</li>
          <li class="list-item">Listen!</li>
        </ul>
      </div>
    </div>
    <div class="form-of">
      <div>
        <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
        <h3>Form</h3>
      </div>
      <p>to be (<span style="font-style: italic;">am, are, is</span>) + <span class="infinitive">infinitive</span> + <span class="ending">-ing</span></p>
    </div>
    <div class="examples">
      <div class="affirmative-sentences">
        <div>
          <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
          <h3>Affirmative sentences in the <span style="font-style: italic;">Present Continuous</span></h3>
        </div>
        <div class="tbl">
          <table>
            <thead>
              <tr>
                <td>Long forms</td>
                <td>Contracted forms</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>I <span class="auxiliary">am</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>I'<span class="auxiliary">m</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td>You <span class="auxiliary">are</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>You'<span class="auxiliary">re</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td>He <span class="auxiliary">is</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>He'<span class="auxiliary">s</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="negative-sentences">
        <div>
          <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
          <h3>Negative sentences in the <span style="font-style: italic;">Present Continuous</span></h3>
        </div>
        <div class="tbl">
          <table>
            <thead>
              <tr>
                <td>Long forms</td>
                <td>Contracted forms</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>I <span class="auxiliary">am</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>I'<span class="auxiliary">m</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td rowspan="2">You <span class="auxiliary">are</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>You'<span class="auxiliary">re</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td>You <span class="auxiliary">are</span><span class="negation">n't</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td rowspan="2">He <span class="auxiliary">is</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
                <td>He'<span class="auxiliary">s</span> <span class="negation">not</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
              <tr>
                <td>He <span class="auxiliary">is</span><span class="negation">n't</span> <span class="infinitive">play</span><span class="ending">ing</span> football.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="questions">
        <div>
          <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
          <h3>Questions in the <span style="font-style: italic;">Present Continuous</span></h3>
        </div>
        <div class="tbl">
          <table>
            <thead>
              <tr>
                <td>Long forms</td>
                <td>Contracted forms</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><span class="auxiliary">Am</span> I <span class="infinitive">play</span><span class="ending">ing</span> football?</td>
                <td rowspan="3">not possible</td>
              </tr>
              <tr>
                <td><span class="auxiliary">Are</span> you <span class="infinitive">play</span><span class="ending">ing</span> football?</td>
              </tr>
              <tr>
                <td><span class="auxiliary">Is</span> he <span class="infinitive">play</span><span class="ending">ing</span> football?</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="try-tasks">
      <img class="point" src="{% static 'learntenses/images/point.png' %}" alt="">
      <h3>Ready to solve some tasks? Take a shot at <a href="{% url 'home:task_list' 'present_continuous' %}" style="text-decoration: none; color:#f49f0a">them</a>!</h3>
    </div>
    <div class="grammar-credit">
      <p>Grammar taken from <a href="https://www.englisch-hilfen.de/en/inhalt_grammar.htm">englisch-hilfen.de</a></p>
    </div>
  </div>
</div>  

{% endblock %}